### ISSUE TITLE
В классах Ball и Wall неверное именование переменных

### ISSUE THREAD

**Issue by sergey-shambir** [bogdanov-d-a/PlatformJumper#1]
Строка
`auto m_wallPuppeteer = NodePhysicsPuppeteer::create(this, wallBodyDef, physEngine);`
объявляет локальную переменную, но в названии переменной присутствует m_. Возможно, здесь имелся ввиду всё-таки член класса.

**Comment by bogdanov-d-a** [comment]
Здесь надо часть m_ убрать, она осталась после правки кода.
