### ISSUE TITLE
Ссылка на объекты типа Puppeteer

### ISSUE THREAD

**Issue by sergey-shambir** [bogdanov-d-a/PlatformJumper#2]
В данный момент PhysicsPuppeteer унаследован от класса Node и добавляется на сцену. В этом нет необходимости - puppeteer не имеет визуального представления и не является узлом сцены. По сути, добавление его на сцену через addChild используется лишь для контроля времени жизни.

Есть альтернативный способ контроля времени жизни - умный указатель. Обычный shared_ptr или unique_ptr для кокоса не подходит из-за того, что любой cocos2d::Object уже содержит счётчик ссылок. Можно наследовать PhysicsPuppeteer от cocos2d::Object и использовать такой умный указатель:
https://github.com/RoadToExclusivity/CocosPhysics/blob/master/Classes/Pointer.h

**Comment by bogdanov-d-a** [comment]
Исправлено; теперь время жизни PhysicsPuppeteer контролируется вызовами retain / release.

**Comment by sergey-shambir** [comment]
Это хороший подход, но RAII лучше. Умный указатель как член класса Ball мог бы контроллировать своевременный вызов retain/release BallPuppeteer с гарантией отсутствия ошибок.

https://en.wikipedia.org/wiki/Resource_Acquisition_Is_Initialization

**Comment by bogdanov-d-a** [comment]
Реализован ObjectKeeper, использующий подход RAII.
